[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.branch-deploy]
  [context.branch-deploy.environment]
    VUE_APP_ATLPOWER_BASE_APIURL = "https://altpower.herokuapp.com/v1"
    VUE_APP_MODE = "staging"
    
[context.production]
  [context.production.environment]
    VUE_APP_MODE = "production"