export default {
  batteries: [],
  inverters: [],
  panels: [],
  bundles: [],
  productsList: [],
  productDetails: {},
  productSlug: "",
  productId: "",
  similarProducts: [],
  pagination: "",
  loading: true,
  page: 1,
  show: true,
};
